- hosts: webserver
  vars_files:
          haproxy_var.yml
  tasks:
  - name: Installing httpd software 
    package:
            name: httpd
            state: present 

  - name: Installing PHP software
    package:
            name: php
            state: present 

  - name: Copy the Webpages to the root directory 
    template:
            src: index.php
            dest: /var/www/html/index.php
    notify:
    - Restart httpd

  - name: Start the service 
    service:
            name: httpd
            state: started

  handlers:
  - name: Restart httpd
    service:
            name: httpd
            state: restarted
 


- hosts: HAProxy
  vars_files:
          haproxy_var.yml
  tasks:
  - name: Installing HAProxy software
    package:
           name: haproxy
           state: present

  - name: Configure the configuration file of haproxy 
    template:
            src: haproxy.cfg
            dest: /etc/haproxy/haproxy.cfg 
    notify:
    - Restart haproxy

  - name: Start the service 
    service:
             name: haproxy
             state: started

  handlers:
  - name: Restart haproxy 
    service:
              name: haproxy
              state: restarted  
